// <auto-generated />
using System;
using BullkyBook.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreTest2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221013074205_AddCategoryTbl")]
    partial class AddCategoryTbl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoreTest2.Models.BullkyBookModel", b =>
                {
                    b.Property<int>("book_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("book_Id"), 1L, 1);

                    b.Property<string>("book_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("display_Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("oder_date")
                        .HasColumnType("datetime2");

                    b.HasKey("book_Id");

                    b.ToTable("bullkyBookModels");
                });
#pragma warning restore 612, 618
        }
    }
}
